name: LogParser Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      env:
        NODE_ENV: test
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEST_TIMESTAMP: '2025-02-19 11:16:50'
        TEST_USER: 'dax-side'
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-2025-02-19-111650
        path: test-results.json
        retention-days: 14
        compression-level: 6
        overwrite: true
