name: LogParser Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Use default GITHUB_TOKEN permissions
permissions:
  contents: write  # Needed for pushing changes
  actions: read    # For reading workflow info

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0   # Get all history for proper updates
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-2025-02-21-083358
        path: |
          test/test-results.txt
        retention-days: 14
        compression-level: 6
        overwrite: true
        if-no-files-found: warn

    - name: Update test results text file
      run: |
        echo "Test Results Summary" > test/test-results.txt
        echo "===================" >> test/test-results.txt
        echo "Timestamp: 2025-02-21 08:33:58" >> test/test-results.txt
        echo "User: dax-side" >> test/test-results.txt
        echo "" >> test/test-results.txt
        cat test/test-results.json >> test/test-results.txt

    - name: Push test results
      if: github.event_name != 'pull_request'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull origin main
        git add test/test-results.txt
        git commit -m "test: update results from CI run

        Timestamp: 2025-02-21 08:33:58
        User: dax-side

        - Store test execution results
        - Update parser statistics
        - Record current timestamp
        - Update text results file
        - CI run: ${GITHUB_RUN_ID}" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ github.token }}  # Use default token
